version: '3.8'

services:
  drupal:
    build:
      context: .  # Указываем контекст сборки - текущий каталог
      dockerfile: Dockerfile  # Указываем имя Dockerfile, если оно отличается от default
    image: custom-drupal:latest  # Ваш образ, собранный с Dockerfile
    ports:
      - "8080:80"
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
    volumes:
      - drupal-data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  drupal-data:
  db-data:
